simplify naming

diff --git a/bin/snapback b/bin/snapback
--- a/bin/snapback
+++ b/bin/snapback
@@ -14,30 +14,30 @@ source libsnap.sh || exit 1
 
 
 for dir in /usr/local/etc /etc; do [[ -d $dir/$our_name ]] && break; done
-readonly   backup_config_dir=$dir/$our_name
-readonly backup_exclude_file=$backup_config_dir/exclude.txt$sample_suffix
-readonly  backup_config_file=$backup_config_dir/configure.sh$sample_suffix
-readonly  backup_config_file_sample=${backup_config_file%.sample}.sample
+readonly   config_dir=$dir/$our_name
+readonly exclude_file=$config_dir/exclude.txt$sample_suffix
+readonly  config_file=$config_dir/configure.sh$sample_suffix
+readonly  config_file_sample=${config_file%.sample}.sample
 
-if [[ ! -s $backup_config_file_sample ]]
-   then abort "have to install $backup_config_file_sample"
-elif ! head -n1  $backup_config_file_sample | fgrep -q -x "# version=$version"
-   then abort "$backup_config_file_sample version does not match $our_name"
+if [[ ! -s $config_file_sample ]]
+   then abort "have to install $config_file_sample"
+elif ! head -n1  $config_file_sample | fgrep -q -x "# version=$version"
+   then abort "$config_file_sample version does not match $our_name"
 fi
 
 # for each config var, create associative array for per-drive customization
 readonly uncustomizable_config_vars="
 		backup_dir_prefix old_crypt_name_prefixes drive_config_file"
-readonly config_vars=$(sed '/() *{/,/^}/d' $backup_config_file_sample |
+readonly config_vars=$(sed '/() *{/,/^}/d' $config_file_sample |
 		       sed -n -r 's/^[^#=]*\b(\w+)=.*$/\1/p' | sort -u)
 for var in $config_vars; do eval "declare -A bkp_name2$var"; done
 #
 # this grabs variables that control backup and pruning, and also gets
 # (customizable) functions set_backup_name & source_drive_specific_config_file
-source $backup_config_file || abort "$backup_config_file broken"
+source $config_file || abort "$config_file broken"
 
-[[ -s $backup_exclude_file ]] ||
-   abort "install/edit $backup_exclude_file, see included .sample"
+[[ -s $exclude_file ]] ||
+   abort "install/edit $exclude_file, see included .sample"
 
 Usage="
 Usage: $our_name action [args]
@@ -52,7 +52,7 @@ Usage: $our_name action [args]
     kill-prune name(s) : for each name (can be 'all'), kill prune
     kill-both name(s)  : for each name (can be 'all'), kill backup & prune
 
-    add-extN-journal backup_name [FS_device]: backup gets external journal
+    add-extN-journal backup_name [FS_device]: current backup gets fast journal
     mkfs device [name]: prepare blank first- or smallest-drive (see comments)
     copy-backup {src_name | ''} dst_name dst_dev: copy (default oldest) to dst
     mk-Z [date [period]]: create mostly-empty snapshot dirs in Z mount-point
@@ -126,7 +126,7 @@ FUNCNEST=100				# catch coding errors
 # miscellaneous variables and functions used by for making and pruning backups
 # ----------------------------------------------------------------------------
 
-# touched when prune ends; its time is compared to files in $backup_config_dir/
+# touched when prune ends; its time is compared to files in $config_dir/
 readonly pruned_timestamp=.pruned.ts
 
 readonly our_opts=${our_opts# }
@@ -292,9 +292,9 @@ have_cmd \
 source_drive_specific_config_file ||  # configure.sh can replace this function
 source_drive_specific_config_file() {
 	[[ $# == 0 ]] && return
-	local _name=$1  _main_config_file=${2:-${backup_config_file-}}
+	local _name=$1  _main_config_file=${2:-${config_file-}}
 	set_backup_name $_name
-	[[ $_main_config_file ]] || abort "pass backup_config_file as 2nd arg"
+	[[ $_main_config_file ]] || abort "pass config_file as 2nd arg"
 
 	local     _config_file=${_main_config_file/%.sh/-$backup_name.sh}
 	if [[ -s $_config_file ]]
@@ -509,7 +509,7 @@ customize_config_variables() {
 	[[ $dir ]] || return
 
 	set_backup_name $dir ||
-	   abort "$backup_config_file needs set_backup_name function"
+	   abort "$config_file needs set_backup_name function"
 
 	[[ $backup_name == Z ]] && is_regression_test=$true
 
@@ -521,7 +521,7 @@ customize_config_variables() {
 
 		eval "local custom_value=\${$array_name[\$backup_name]-}"
 		is_arg1_in_arg2 $var_name $uncustomizable_config_vars &&
-		   abort "$backup_config_file can't have custom '$var_name'"
+		   abort "$config_file can't have custom '$var_name'"
 		eval "$var_name=\$custom_value"
 		set +x
 		Trace 2 "$array_name[$backup_name] -> $var_name=$custom_value"
@@ -534,7 +534,7 @@ validate_config_variables() {
 
 	declare -p $config_vars | grep -v '^declare -'
 	[[ ${PIPESTATUS[0]} == 0 ]] ||
-	    abort "must assign above variables, see $backup_config_file_sample"
+	    abort "must assign above variables, see $config_file_sample"
 
 	local var=snapshot_date_time_separator
 	[[ ${!var} == ',' ]] ||
@@ -550,7 +550,7 @@ validate_config_variables() {
 	[[ ${custom_dirs_to_backup-} ]] && # from interactive user
 	            dirs_to_backup=$custom_dirs_to_backup
 
-	set -- $backup_config_file $drive_config_file
+	set -- $config_file $drive_config_file
 
 	echo " $dirs_to_backup " | grep ' [^/]' &&
 	   abort "dirs_to_backup contains a non-absolute path in $*"
@@ -625,9 +625,9 @@ _is_time_to_prune_backup() {
 	local pruned_TS=$dir/$pruned_timestamp
 
 	[[ ! -e $pruned_TS ]] && return 0 # never finished a prune?
-	[[ $pruned_TS -ot $backup_config_file  ]] && return 0 # newer config?
-	[[ $pruned_TS -ot $backup_exclude_file ]] && return 0 # newer excludes?
-	[[ $(find $pruned_TS ! -mtime 0) ]] && return 0	      # older prune?
+	[[ $pruned_TS -ot $config_file   ]] && return 0 # newer config?
+	[[ $pruned_TS -ot $exclude_file  ]] && return 0 # newer excludes?
+	[[ $(find $pruned_TS ! -mtime 0) ]] && return 0	# older prune?
 
 	return 1			# not time to prune
 }
@@ -709,13 +709,13 @@ _rm_pruned_snapshots() {
 	   ( ! $RunIf &&		# ... too slow for real drive
 	     # very slow: only run if exclude.txt changed since our last run
 	     ( ! -e $pruned_TS ||
-		    $pruned_TS -ot $backup_exclude_file ) ) ]] &&
+		    $pruned_TS -ot $exclude_file ) ) ]] &&
 	{
 	# prune exclude-patterns from _all_ snapshots, very slow
 	local exclude_pattern file
 	for snapshot in $backup_dir/$snapshot_pattern*
 	    do	[[ $snapshot == *.rm ]] && continue
-		grep '^ */' $backup_exclude_file | fgrep -v '**' |
+		grep '^ */' $exclude_file | fgrep -v '**' |
 		while read exclude_pattern
 		    do	set -- $snapshot$exclude_pattern
 			for file	# can have SPACEs, need to quote it
@@ -1008,7 +1008,7 @@ _links_error_msg() {
 	msg="$msg; Worst case, tried to add $max_src_links links to a snapshot file; these files will eventually appear in a new snapshot after $link_dest_wait hours; $# snapshots waiting to be pruned, newer prunes subtract ~$max_src_links links"
 
 	[[ $hostname != eleanor ]] &&
-	msg="$msg; Edit prune variables in $backup_config_file to reduce # snapshots"
+	msg="$msg; Edit prune variables in $config_file to reduce # snapshots"
 
 	echo "$msg"
 }
@@ -1147,7 +1147,7 @@ run_backup() {
 
 	$Trace
 
-	# most of these variables come from $backup_config_file
+	# most of these variables come from $config_file
 	$RunIf rsync $rsync_backup_opts $our_rsync_opts	\
 	   --relative $link_dest_opts			\
 	   --exclude=$backup_dir_prefix*		\
@@ -1410,7 +1410,7 @@ case $action in
    ( r*b*k*p* | rb* )
 	is_arg1_in_arg2 $# "0 1 2 3" ||	# guard against -s without ''
 	   abort "wrong number of args, run: $_our_name -h"
-	# to use -s, must remove 'readonly' label in $backup_config_file
+	# to use -s, must remove 'readonly' label in $config_file
 	[[ ${1-} == -s ]] && { custom_dirs_to_backup="$2"; shift 2; }
 
 	set -- ${*:-$(list_backups)}
@@ -1438,7 +1438,7 @@ case $action in
 	;;
    # prune-backups [span] [dirs]: see configure.sh; dirs defaults to all drives
    ( pr*n*b*k*p* | pb* )
-	# if specify span, must remove 'readonly' label in $backup_config_file
+	# if specify span, must remove 'readonly' label in $config_file
 	[[ ${1-} == [0-9]* ]] && { hour_prune_days_per_span=$1; shift; }
 
 	set -- ${*:-$(list_backups)}
@@ -1728,7 +1728,7 @@ case $action in
    # sysadmin maintenance actions
    ###########################################################################
 
-   # add-extN-journal backup_name [FS_device]: backup gets external journal
+   # add-extN-journal backup_name [FS_device]: current backup gets fast journal
    ( add-ext-journal | aej )
 	[[   $# == [12] ]] || abort "backup_name [device]"
 	name=$1 FS_device=${2-}
