Create actions to manipulate snapshots: rm, unrm, redo

diff --git a/bin/snapback b/bin/snapback
--- a/bin/snapback
+++ b/bin/snapback
@@ -165,6 +165,10 @@ Usage: $our_name [options] action [options] [args]
     update-drives  [-s src-names-glob] dst-names: copy missing snapshots
     copy-snapshots [-B] [-q] snapshots name: copy to 'name' mounted drive
 
+      rm snapshots: rename snapshots to *.rm, so they'll be pruned (rm -rf)
+    unrm snapshots: rename *.rm snapshots to *.partial (update-drive restores)
+    redo snapshots: rename      snapshots to *.partial (update-drive restores)
+
     w: show full details on all jobs and drives
     watch [-s][-C][-N names] [watch-opts]: dashboard (-s: stats; -C: cron jobs)
     big-swapouts: search syslog files for warnings about high swapout rates
@@ -6953,6 +6957,33 @@ case $action in
 	src_snapshots=${*%$drive_name}
 	src_snapshots=${src_snapshots% }
 	create-jobs copy -s${src_snapshots// / -s} $opts $drive_name
+	;;
+
+   # rm snapshots: rename snapshots to *.rm, so they'll be pruned (rm -rf)
+   ( rm | del* ) undo-action-abbrev rm
+	for snapshot
+	    do	[[ $snapshot != *.rm ]] || continue
+		$IfRun sudo mv -v $snapshot $snapshot.rm
+	done
+	;;
+   # unrm snapshots: rename *.rm snapshots to *.partial (update-drive restores)
+   ( unrm | undel* ) undo-action-abbrev unrm
+	for snapshot
+	    do	[[ $snapshot == *.rm ]] || warn "$snapshot not *.rm" || continue
+		if  [[ $snapshot == *.partial.rm ]]
+		   then $IfRun sudo mv -v $snapshot ${snapshot%.rm}
+		   else $IfRun sudo mv -v $snapshot ${snapshot%.rm}.partial
+		fi
+	done
+	;;
+   # redo snapshots: rename      snapshots to *.partial (update-drive restores)
+   ( redo )
+	for snapshot
+	    do	[[ $snapshot != *.rm ]] || warn "can't redo *.rm; see unrm" ||
+		    continue
+		[[ $snapshot == *,[0-2][0-9] ]] || continue
+		$IfRun sudo mv -v $snapshot $snapshot.partial
+	done
 	;;
 
    ###########################################################################
