Use $$ not $BASHPID in tmp files, in case use a tmp file in a (forked) pipeline stage. Move the test action to the very end, since it's boring to read.

diff --git a/bin/snapback b/bin/snapback
--- a/bin/snapback
+++ b/bin/snapback
@@ -138,11 +138,11 @@ unset arg
 trap '' HUP TERM
 trap 'set +x; rm -f $tmp_1 $tmp_2 $tmp_3 $tmp_4 $tmp_5; trap EXIT' EXIT
 
-readonly tmp_1=$tmp_dir/$our_name-1-$BASHPID	; tmp=$tmp_1
-readonly tmp_2=$tmp_dir/$our_name-2-$BASHPID
-readonly tmp_3=$tmp_dir/$our_name-3-$BASHPID
-readonly tmp_4=$tmp_dir/$our_name-4-$BASHPID
-readonly tmp_5=$tmp_dir/$our_name-5-$BASHPID
+readonly tmp_1=$tmp_dir/$our_name-1-$$	; tmp=$tmp_1
+readonly tmp_2=$tmp_dir/$our_name-2-$$
+readonly tmp_3=$tmp_dir/$our_name-3-$$
+readonly tmp_4=$tmp_dir/$our_name-4-$$
+readonly tmp_5=$tmp_dir/$our_name-5-$$
 
 need_cmds lockpid
 
@@ -3091,113 +3091,8 @@ case $action in
 	;;
 
    ###########################################################################
-   # Actions for random testing, followed by regression tests.
+   # Actions for regression tests.
    ###########################################################################
-
-   ( test | t )
-	validate_config_variables
-	set__OS_release_file__OS_release
-	TraceV 0 OS_release_file OS_release
-	exit
-
-	wont_trace() {         foo=2
-		       suspend_tracing; echo untraced; restore_tracing foo; }
-	will_trace() { set -x; foo=1
-		       suspend_tracing; echo untraced; restore_tracing foo
-		       wont_trace; echo traced; set +x; }
-	will_trace
-	exit
-
-	log test 1
-	customize_and_validate_configuration_variables Z
-	echo $drive_name
-	log test 2
-	exit
-
-	set_FS_block_size___from_path $1
-	echo $FS_block_size
-	exit
-
-	for dev in $(df | cut -d' ' -f1)
-	    do	[[ -b $dev ]] || continue
-		set_FS_label___from_FS_device $dev
-		echo "$dev -> $FS_label"
-	done
-	exit
-
-	for path in /backup/A /backup/A/latest /dev/sdb5
-	    do	set_FS_type___from_path $path
-		echo "$path -> $FS_type"
-	done
-	exit
-
-	print_call_stack 1
-	abort test
-
-	set_drive_name ${1:-a}
-	TraceV 0 drive_name file_for_logging log_msg_prefix
-	echo  test1
-	echoE test2
-	log 0 test3
-	abort test4
-	exit
-
-	copy_snapshot 1 2 3
-	exit
-
-	echoE test
-	foo() {
-		echoE ftest
-		for  i  in ${!FUNCNAME[*]}
-		   do	echo "FUNCNAME[i]=${FUNCNAME[$i]}"
-		done
-		echoEV   i
-		TraceV 0 i i
-		abort "aborting test"
-	}
-	foo
-	exit
-
-	set_drive_name ${1:-a}
-	set_drive_dir $drive_name
-	set_FS_label___from_mount_dir $drive_dir
-	echo $FS_label
-	exit
-
-	set_drive_dir ${1^}
-	$Trace
-	is_disk_usage_too_high
-	abort $?
-
-	set_oldest_snapshot
-	echo $oldest_snapshot
-	exit
-
-	for size in 1023 1024 2123123 3123123123 4123123123123 5123123123123123
-	    do	set_readable_du_size $size; echo "$readable_du_size from $size"
-	done
-	exit
-
-	drive_dir=/backup/F
-	cd $drive_dir
-	log=/tmp/root/F-190126-15.bz2
-	_links_error_msg "nnn 'Too many links'"
-	exit
-
-	set_drive_dir F
-	exit
-
-	$Trace
-	set_drive_dir ${1-''}
-	log "test with drive ${1-}"
-	exit
-
-	echo $backup_period
-	customize_config_variables F
-	echo $backup_period
-	backup_period+=1
-	echo $backup_period
-	;;
 
    # mk-Z [date [period]]: create mostly-empty snapshot dirs in Z mount-point
    ( mk*[Zz] | mkz )
@@ -3402,6 +3297,116 @@ case $action in
    ( drive )
 	set_drive_name $1
 	echo $drive_dir_prefix$drive_name
+	;;
+
+   # -------------------------------------------------------------
+   # this final action has random tests used during development; #
+   # you can jump to the end of the file.			 #
+   # -------------------------------------------------------------
+
+   ( test | t )
+	validate_config_variables
+	set__OS_release_file__OS_release
+	TraceV 0 OS_release_file OS_release
+	exit
+
+	wont_trace() {         foo=2
+		       suspend_tracing; echo untraced; restore_tracing foo; }
+	will_trace() { set -x; foo=1
+		       suspend_tracing; echo untraced; restore_tracing foo
+		       wont_trace; echo traced; set +x; }
+	will_trace
+	exit
+
+	log test 1
+	customize_and_validate_configuration_variables Z
+	echo $drive_name
+	log test 2
+	exit
+
+	set_FS_block_size___from_path $1
+	echo $FS_block_size
+	exit
+
+	for dev in $(df | cut -d' ' -f1)
+	    do	[[ -b $dev ]] || continue
+		set_FS_label___from_FS_device $dev
+		echo "$dev -> $FS_label"
+	done
+	exit
+
+	for path in /backup/A /backup/A/latest /dev/sdb5
+	    do	set_FS_type___from_path $path
+		echo "$path -> $FS_type"
+	done
+	exit
+
+	print_call_stack 1
+	abort test
+
+	set_drive_name ${1:-a}
+	TraceV 0 drive_name file_for_logging log_msg_prefix
+	echo  test1
+	echoE test2
+	log 0 test3
+	abort test4
+	exit
+
+	copy_snapshot 1 2 3
+	exit
+
+	echoE test
+	foo() {
+		echoE ftest
+		for  i  in ${!FUNCNAME[*]}
+		   do	echo "FUNCNAME[i]=${FUNCNAME[$i]}"
+		done
+		echoEV   i
+		TraceV 0 i i
+		abort "aborting test"
+	}
+	foo
+	exit
+
+	set_drive_name ${1:-a}
+	set_drive_dir $drive_name
+	set_FS_label___from_mount_dir $drive_dir
+	echo $FS_label
+	exit
+
+	set_drive_dir ${1^}
+	$Trace
+	is_disk_usage_too_high
+	abort $?
+
+	set_oldest_snapshot
+	echo $oldest_snapshot
+	exit
+
+	for size in 1023 1024 2123123 3123123123 4123123123123 5123123123123123
+	    do	set_readable_du_size $size; echo "$readable_du_size from $size"
+	done
+	exit
+
+	drive_dir=/backup/F
+	cd $drive_dir
+	log=/tmp/root/F-190126-15.bz2
+	_links_error_msg "nnn 'Too many links'"
+	exit
+
+	set_drive_dir F
+	exit
+
+	$Trace
+	set_drive_dir ${1-''}
+	log "test with drive ${1-}"
+	exit
+
+	echo $backup_period
+	customize_config_variables F
+	echo $backup_period
+	backup_period+=1
+	echo $backup_period
 	;;
 
    ( * )
