re-order FS-related functions

diff --git a/bin/snapback b/bin/snapback
--- a/bin/snapback
+++ b/bin/snapback
@@ -4957,126 +4957,6 @@ monitor-drives() {
 readonly -f monitor-drives
 
 # ----------------------------------------------------------------------------
-# miscellaneous functions for later functions
-# ----------------------------------------------------------------------------
-
-# for each name (can be 'all'), kill any backups/pruning/etc & unmount drive
-function unmount-drives() {
-	[[ $1 == -q  ]] && { local quiet_opt=$1; shift; } || local quiet_opt=
-	assert-not-option "${1-}"
-	[[ $* == all ]] && set -- $(list-drive-dirs)
-
-	$Trace
-	# do this early, since takes a while for processes to die
-	for name
-	    do	$IfRun kill-job-on-drives all $name
-	done
-
-	[[ $debug_opt ]] && local output=/dev/stdout || local output=/dev/null
-	local name drive_name drive_dir status=0
-	for name
-	    do	set-drive_name $name
-		set-drive_dir $quiet_opt $drive_name
-		is-drive-mounted $drive_dir || continue
-		sudo umount -h &> /dev/null || warn "need sudo privs" || break
-		umount_cmd="$IfRun sudo umount -v $drive_dir"
-		for _i in {1..99}	# wait for kill to finish
-		    do	$umount_cmd && break
-			$IfRun sleep 0.1
-		done &> $output
-		is-drive-mounted $drive_dir || continue
-		$umount_cmd || status=$? # this time, show the error message
-	done
-	return $status
-}
-readonly -f unmount-drives
-
-# ----------------------------------------------------------------------------
-
-# Optional function to allocate an external filesystem log/journal
-# on fast storage (SSD, or always-plugged-in flash memory stick),
-# for use with rotational hard disks.
-# Rewrite this function if you're not using LVM.
-have-cmd set-FS_external_log ||	   # can define custom version in $config_file
-function set-FS_external_log() {
-	[[ ${1-} == -f ]] && { local force_opt=$1; shift; } || local force_opt=
-	local FS_label=$1 VG=${2:-${FS_log_VG-}} # FS_log_VG in $config_file
-
-	[[ $VG ]] &&
-	[[ $do_want_external_log ||	# defined in $config_file
-	   $force_opt               ]] || { FS_external_log= && return 1; }
-
-	[[ $VG ]] ||
-	   abort "must define set-FS_external_log or FS_log_VG in $config_file"
-
-	       FS_external_log=/dev/$VG/${FS_label}_log
-	[[ -b $FS_external_log ]] && return 0
-
-	$IfRun lvcreate --size 128M --name $FS_external_log $VG ||
-	    FS_external_log=
-	[[ $FS_external_log ]]
-}
-readonly -f set-FS_external_log
-
-# ----------------------------------------------------------------------------
-
-# add-extN-journal drive_name [FS_device [VG_name]]: fast external journal
-function add-extN-journal() {
-	[[ ${1-} == -M ]] && { local  do_mount=  ; shift; } || local do_mount=t
-	[[ ${1-} == -f ]] && { local force_opt=$1; shift; } || local force_opt=
-	[[ $# == [1-4] ]] ||
-	   abort "{-l FS_label | drive_name} [device [VG-name]]"
-	if [[ $1 == -l ]]
-	   then shift;  local FS_label=$1
-	   else local name=$1 FS_label=
-	fi
-	assert-not-option -o "${1-}"
-	local FS_device=${2-} VG_name=${3-}
-
-	[[ $UID == 0 ]] || $IfRun abort "run with sudo"
-
-	[[ ! $FS_label ]] && {
-	set-drive_name -q $1
-	set-drive_dir $drive_name
-	mount_dir=$drive_dir
-	set-FS_label--from-mount_dir $mount_dir ; }
-							[[ $FS_device ]] ||
-	set-FS_device--from-FS-label $FS_label
-	[[ ${mount_dir-} ]] ||
-	   set-mount_dir--from-FS-label  $FS_label ||
-	   set-mount_dir--from-FS-device $FS_device
-	TraceV 1 force_opt FS_label FS_device VG_name mount_dir
-
-	sudo tune2fs -l $FS_device | grep -q '^Journal ' &&	  {
-	warn "removing internal journal can take many minutes"
-	$IfRun tune2fs $force_opt -O ^has_journal $FS_device	; }
-
-	set-FS_external_log $force_opt $FS_label $VG_name ||
-	warn "invalid set-FS_external_log, or $config_file says log unwanted"||
-	   { $IfRun tune2fs -j $FS_device; return $?; }
-	label=${FS_external_log##*/}
-
-	$Trace
-
-	RunCmd mke2fs -v -b 4096 -O journal_dev -L $label $FS_external_log
-
-	suspend-tracing
-	RunCmd -d unmount-drives -q ${mount_dir:-$FS_device}
-	restore-tracing
-	mount | fgrep -w $FS_device && $IfRun abort "must: umount $FS_device"
-
-	RunCmd tune2fs -J device=LABEL=$label $FS_device
-	$IfRun tune2fs -l $FS_device | grep -i "journal [id]"
-	local status=${PIPESTATUS[0]}
-
-	[[ $do_mount ]] || return $status
-
-	mount_options=$common_mount_options,$extN_mount_options
-	RunCmd mount -v -t ext4 -o ${mount_options%,} $FS_device $mount_dir
-}
-readonly -f add-extN-journal
-
-# ----------------------------------------------------------------------------
 # functions to calculate directory sizes for different FS parameters
 # ----------------------------------------------------------------------------
 
@@ -5277,6 +5157,126 @@ filesystem-geometry() {
 	rm -f $tmp_1
 }
 readonly -f filesystem-geometry
+
+# ----------------------------------------------------------------------------
+# miscellaneous functions for later functions
+# ----------------------------------------------------------------------------
+
+# for each name (can be 'all'), kill any backups/pruning/etc & unmount drive
+function unmount-drives() {
+	[[ $1 == -q  ]] && { local quiet_opt=$1; shift; } || local quiet_opt=
+	assert-not-option "${1-}"
+	[[ $* == all ]] && set -- $(list-drive-dirs)
+
+	$Trace
+	# do this early, since takes a while for processes to die
+	for name
+	    do	$IfRun kill-job-on-drives all $name
+	done
+
+	[[ $debug_opt ]] && local output=/dev/stdout || local output=/dev/null
+	local name drive_name drive_dir status=0
+	for name
+	    do	set-drive_name $name
+		set-drive_dir $quiet_opt $drive_name
+		is-drive-mounted $drive_dir || continue
+		sudo umount -h &> /dev/null || warn "need sudo privs" || break
+		umount_cmd="$IfRun sudo umount -v $drive_dir"
+		for _i in {1..99}	# wait for kill to finish
+		    do	$umount_cmd && break
+			$IfRun sleep 0.1
+		done &> $output
+		is-drive-mounted $drive_dir || continue
+		$umount_cmd || status=$? # this time, show the error message
+	done
+	return $status
+}
+readonly -f unmount-drives
+
+# ----------------------------------------------------------------------------
+
+# Optional function to allocate an external filesystem log/journal
+# on fast storage (SSD, or always-plugged-in flash memory stick),
+# for use with rotational hard disks.
+# Rewrite this function if you're not using LVM.
+have-cmd set-FS_external_log ||	   # can define custom version in $config_file
+function set-FS_external_log() {
+	[[ ${1-} == -f ]] && { local force_opt=$1; shift; } || local force_opt=
+	local FS_label=$1 VG=${2:-${FS_log_VG-}} # FS_log_VG in $config_file
+
+	[[ $VG ]] &&
+	[[ $do_want_external_log ||	# defined in $config_file
+	   $force_opt               ]] || { FS_external_log= && return 1; }
+
+	[[ $VG ]] ||
+	   abort "must define set-FS_external_log or FS_log_VG in $config_file"
+
+	       FS_external_log=/dev/$VG/${FS_label}_log
+	[[ -b $FS_external_log ]] && return 0
+
+	$IfRun lvcreate --size 128M --name $FS_external_log $VG ||
+	    FS_external_log=
+	[[ $FS_external_log ]]
+}
+readonly -f set-FS_external_log
+
+# ----------------------------------------------------------------------------
+
+# add-extN-journal drive_name [FS_device [VG_name]]: fast external journal
+function add-extN-journal() {
+	[[ ${1-} == -M ]] && { local  do_mount=  ; shift; } || local do_mount=t
+	[[ ${1-} == -f ]] && { local force_opt=$1; shift; } || local force_opt=
+	[[ $# == [1-4] ]] ||
+	   abort "{-l FS_label | drive_name} [device [VG-name]]"
+	if [[ $1 == -l ]]
+	   then shift;  local FS_label=$1
+	   else local name=$1 FS_label=
+	fi
+	assert-not-option -o "${1-}"
+	local FS_device=${2-} VG_name=${3-}
+
+	[[ $UID == 0 ]] || $IfRun abort "run with sudo"
+
+	[[ ! $FS_label ]] && {
+	set-drive_name -q $1
+	set-drive_dir $drive_name
+	mount_dir=$drive_dir
+	set-FS_label--from-mount_dir $mount_dir ; }
+							[[ $FS_device ]] ||
+	set-FS_device--from-FS-label $FS_label
+	[[ ${mount_dir-} ]] ||
+	   set-mount_dir--from-FS-label  $FS_label ||
+	   set-mount_dir--from-FS-device $FS_device
+	TraceV 1 force_opt FS_label FS_device VG_name mount_dir
+
+	sudo tune2fs -l $FS_device | grep -q '^Journal ' &&	  {
+	warn "removing internal journal can take many minutes"
+	$IfRun tune2fs $force_opt -O ^has_journal $FS_device	; }
+
+	set-FS_external_log $force_opt $FS_label $VG_name ||
+	warn "invalid set-FS_external_log, or $config_file says log unwanted"||
+	   { $IfRun tune2fs -j $FS_device; return $?; }
+	label=${FS_external_log##*/}
+
+	$Trace
+
+	RunCmd mke2fs -v -b 4096 -O journal_dev -L $label $FS_external_log
+
+	suspend-tracing
+	RunCmd -d unmount-drives -q ${mount_dir:-$FS_device}
+	restore-tracing
+	mount | fgrep -w $FS_device && $IfRun abort "must: umount $FS_device"
+
+	RunCmd tune2fs -J device=LABEL=$label $FS_device
+	$IfRun tune2fs -l $FS_device | grep -i "journal [id]"
+	local status=${PIPESTATUS[0]}
+
+	[[ $do_mount ]] || return $status
+
+	mount_options=$common_mount_options,$extN_mount_options
+	RunCmd mount -v -t ext4 -o ${mount_options%,} $FS_device $mount_dir
+}
+readonly -f add-extN-journal
 
 # ----------------------------------------------------------------------------
 # functions leading up to mkfs-backup-drive
