add-extN-journal removes internal journal even if config.sh says don't want a journal: user could have changed their mind, or run copy-backup . Also, add-extN-journal can now more flexibly work with non-backup partitions.

diff --git a/bin/snapback b/bin/snapback
--- a/bin/snapback
+++ b/bin/snapback
@@ -1990,23 +1990,33 @@ case $action in
 
    # add-extN-journal backup_name [FS_device]: current backup gets fast journal
    ( add-extN-journal | aej )
-	[[   $# == [12] ]] || abort "{-l FS_label | backup_name} [device]"
+	[[ ${1-} == -f ]] && { local force_opt=$1; shift; } || local force_opt=
+	[[ $# == [1-4] ]] ||
+	   abort "{-l FS_label | backup_name} [device [VG-name]]"
 	if [[ $1 == -l ]]
 	   then shift;  FS_label=$1
 	   else name=$1 FS_label=
 	fi
-	FS_device=${2-}
+	FS_device=${2-} log_VG_name=${3-}
 
 	[[ $UID == 0 ]] || $IfRun abort "run with sudo"
 
 	[[ ! $FS_label ]] && {
+	is_OK_if_backup_dir_unmounted=$true
 	set_backup_name $1
 	set_backup_dir $backup_name
-	set_FS_label___from_mount_dir $backup_dir ; } ; [[ $FS_device ]] ||
+	set_FS_label___from_mount_dir $backup_dir ; }
+							; [[ $FS_device ]] ||
 	set_FS_device___from_FS_label $FS_label
-	[[ $mount_dir ]] || set_mount_dir___from_FS_device $FS_device
+	[[ ${mount_dir-} ]] || set_mount_dir___from_FS_device $FS_device
+	TraceV 1 force_opt FS_label FS_device log_VG_name mount_dir
 
-	set_FS_external_log $FS_label || abort "need valid set_FS_external_log"
+	tune2fs -l $FS_device | grep -q '^Journal ' &&		  {
+	warn "removing internal journal can take many minutes"
+	$IfRun tune2fs $force_opt -O ^has_journal $FS_device	; }
+
+	set_FS_external_log $force_opt $FS_label $log_VG_name ||
+	 abort "invalid set_FS_external_log, or $config_file says log unwanted"
 	label=$(basename $FS_external_log)
 
 	$Trace
@@ -2020,18 +2030,16 @@ case $action in
 	   grep -v -e ': no filesystem mounted on ' -e '^ *$'
 	is_backup_dir_mounted $backup_dir && $IfRun abort "umount $backup_dir"
 	restore_tracing
-	} || $IfRun umount $FS_device || abort "need to: umount $FS_device"
-
-	tune2fs -l $FS_device | grep -q '^Journal ' &&    {
-	warn "removing internal journal can take many minutes"
-	$IfRun tune2fs -O ^has_journal $FS_device	; }
+	} || $IfRun umount $FS_device &> /dev/null
+	mount  |  fgrep -w $FS_device && $IfRun abort "must: umount $FS_device"
 
 	$IfRun tune2fs -J device=LABEL=$label $FS_device ||
 	   abort "tune2fs -J attempt to attach journal -> $?"
 	$IfRun tune2fs -l $FS_device | grep -i "journal [id]"
 
+	mount_options=$common_mount_options,$ext4_mount_options
 	$IfRun \
-	mount -v -t ext4 -o $mount_options $FS_device $mount_dir ||
+	mount -v -t ext4 -o ${mount_options%,} $FS_device $mount_dir ||
 	   abort "mount exited with $?"
 	;;
 
