Remove early check for unset config variables, it's done later. Turn set-max_drive_names-max_drive_count into did-set-max_drive_names. foo=$(< file) requires a fork, instead use: read-all foo file. Turn re-start-monitor-drives-if-needed into did-re-start-monitor-drives-if-needed, so kill-job-on-drives can reliably report status.

diff --git a/bin/snapback b/bin/snapback
--- a/bin/snapback
+++ b/bin/snapback
@@ -107,25 +107,19 @@ _set-__config_vars__() {
 }
 _set-__config_vars__
 #
-custom_config_maps=
+custom_config_vars=
 for _var in $__config_vars__
     do	[[ $uncustomizable_config_vars == *" $_var "* ]] && continue
-	custom_config_maps+="drv_name2$_var "
+	custom_config_vars+="$_var "
 done
-readonly custom_config_maps
-# shellcheck disable=SC2086 # variable containing multiple values
+readonly    custom_config_vars=${custom_config_vars% }
+readonly    custom_config_maps=drv_name2${custom_config_vars// / drv_name2}
+# shellcheck disable=SC2086 # we want word splitting
 declare -A $custom_config_maps
 #
 # this grabs variables that control backup and pruning, and may also hold
 # customizing functions (like source-drive-specific-config-file and *hooks)
 source "$config_file" || abort "source'd $config_file ended with non-0 status"
-
-for _map in $custom_config_maps
-    do	# shellcheck disable=SC1087 # shellcheck confused by eval
-	eval "[[ \${!$_map[*]} ]]" || continue
-	_var=${_map#drv_name2}
-	[[ -v $_var ]] || abort "can't set $_map without setting $_var"
-done
 
 for _var in $optional_config_vars
     do	[[ -v $_var ]] || __config_vars__=${__config_vars__/ $_var / }
@@ -153,7 +147,7 @@ readonly -f set-FS_label--from-FS-device label-drive
 readonly -f set-FS_device--from-FS-label set-device_KB--from-block-device
 readonly -f set-FS_device--from-path set-mount_dir--from-FS-device
 readonly -f is-arg1-in-arg2 print-call-stack warn abort abort-function
-readonly -f assert-not-option set-var_value--from-var_name echoE echoEV
+readonly -f assert-not-option read-all set-var_value--for-debugger echoE echoEV
 readonly -f Trace TraceV remember-tracing suspend-tracing restore-tracing
 readonly -f print-or-egrep-Usage-then-exit abort-with-action-Usage log header
 readonly -f set-padded_colorized_string--for-printf
@@ -594,6 +588,7 @@ function lock-PID() {
 	    lock_holder_action="is $lock_holder_action"
 
 	[[ $UID == 0 || $debug_opt ]] && local sudo= || local sudo=sudo
+	sudo=	     # fixme: why was sudo needed? it makes test-prune harder
 	lock_opts="--pid=$BASHPID --dir=$lock_dir $lock_opts"
 	local lock_cmd="$sudo lockpid $lock_opts $lock_file"
 	[[ $Trace && ${xtrace-} && ! $IfRun ]] && echo "$PS4 $lock_cmd" >&2
@@ -856,9 +851,8 @@ function set-lock_PGID() {
 	[[ $lock == /* ]] || lock=$lock_dir/${lock##*/}
 	lock_PGID=
 	# shellcheck disable=SC2046 # we want word splitting
-	[[ -s $lock ]] &&
-	set -- $(< "$lock") && [[ $# != 0 ]] || { $xtrace; return 1; }
-	lock_PGID=$1
+	[[ -s $lock ]] && read -r lock_PGID foo < "$lock" &&
+	   [[ $lock_PGID =~ ^[0-9]+$ ]] || { $xtrace; return 1; }
 	$xtrace
 	return 0
 }
@@ -1064,7 +1058,8 @@ function kill-job-on-drives() {
 		   then if [[ $is_monitor_lock ]]
 			   then [[   $type == m* ||
 				   ( $type == a* && $drives == all ) ]] &&
-				re-start-monitor-drives-if-needed -f
+				did-re-start-monitor-drives-if-needed -f &&
+				status=0
 				continue
 			fi
 
@@ -1115,7 +1110,7 @@ function set-lock_PGIDs() {
 	for lock in $locks
 	    do	set-lock_PGID "$lock" || continue
 		lock_PGIDs+=$lock_PGID,
-	done 2> $dev_null	    # a lock might disappear, i.e. $(< ) fails
+	done 2> $dev_null	    # a lock might disappear, i.e. 'read' fails
 	lock_PGIDs=${lock_PGIDs%,}
 	[[ $lock_PGIDs ]]
 }
@@ -1564,34 +1559,34 @@ readonly -f source-drive-specific-config-file
 
 # ----------------------------------------------------------------------------
 
-set-max_drive_names-max_drive_count() {
+max_drive_names=
+
+function did-set-max_drive_names() {
+	[[ -o xtrace ]] && { set +x; local xtrace="set -x"; } || local xtrace=
 
 	pushd_ -q $drive_dir_prefix
-	set -- *[!~]	   # duplicated in update-monitor-config
-	max_drive_count=$# # monitor restarts if # possible mount dirs changes
-	max_drive_names=
-	local name
-	for name
-	    do	[[ $name == nohup.out ]] && continue
-		max_drive_names+="$name "
+	local old_max_drive_names=$max_drive_names
+	local dir
+	for dir in *[!~]
+	    do	[[ -d $dir ]] && max_drive_names+="$dir "
 	done
+	max_drive_names=${max_drive_names% }
 	popd_ -q
+	$xtrace
+	[[ $old_max_drive_names != "$max_drive_names" ]]
 }
-readonly -f set-max_drive_names-max_drive_count
+readonly -f did-set-max_drive_names
 
 # ---------------------------------
 
-	   custom_config_vars=
 declare -A custom_config_var2default_value
 
 fully-populate-custom-config-maps() {
+	did-set-max_drive_names || ! is-set custom_config_var2default_value ||
+	    return
 	[[ -o xtrace ]] && { set +x; local xtrace="set -x"; } || local xtrace=
 
-	[[ $custom_config_vars ]] && { $xtrace; return; }
-
 	remember-tracing		# since suspend-tracing maybe not run
-
-	set-max_drive_names-max_drive_count
 
 	local -A drive_name2class
 	local drive_name
@@ -1602,9 +1597,9 @@ fully-populate-custom-config-maps() {
 	done
 	restore-tracing
 
-	local map_name var_name
-	for map_name in $custom_config_maps
-	    do	var_name=${map_name#drv_name2}
+	local var_name map_name
+	for var_name in $custom_config_vars
+	    do	map_name=drv_name2$var_name
 		[[ -v $var_name ]] || abort "set '$var_name=' in $config_file"
 		local default_value=${!var_name}
 		custom_config_var2default_value[$var_name]=$default_value
@@ -1621,10 +1616,7 @@ fully-populate-custom-config-maps() {
 		done
 	done
 
-	custom_config_vars=${!custom_config_var2default_value[*]}
-	readonly custom_config_vars custom_config_var2default_value
-
-	restore-tracing custom_config_vars
+	restore-tracing
 	$xtrace
 }
 readonly -f fully-populate-custom-config-maps
@@ -1642,7 +1634,7 @@ abort "test fully-populate-custom-config-maps"
 customize-config-variables() {
 	local drive_name=${1-}
 
-	[[ $custom_config_vars ]] ||
+	[[ $max_drive_names ]] ||
 	fully-populate-custom-config-maps
 
 	[[ $drive_name ]] || return
@@ -1831,8 +1823,8 @@ mon-launch-globs() {
 		[[ $# == 0 ]] && true > "$partial_file" ||
 		# snapshot is non-empty if has subdirectories: check link count
 		ls -ld "$@" |
-		    awk '$2 > 2 { print $(NF) }' > "$partial_file.$$" &&
-			     mv "$partial_file.$$" "$partial_file"	  
+		    awk '$2 > 2 { print $(NF) }' >  "$partial_file.new" &&
+			     mv "$partial_file.new" "$partial_file"
 		) &
 		ls_drive_name2PID[$drive_name]=$!
 	done
@@ -1850,7 +1842,7 @@ mon-process-finished-glob() {
 	local -i    start_msecs=${drive_name2msecs[$drive_name]}
 	local -i response_msecs=$epoch_msecs-$start_msecs  window_msecs
 
-	window_msecs=$(< "$window_msecs_dir/$drive_name") ||abort window_msecs=
+	read-all window_msecs "$window_msecs_dir/$drive_name"
 	local -i sample_count=$window_msecs/$mon_check_period_msecs
 	(( $sample_count <= 0 )) && sample_count=1
 
@@ -1865,15 +1857,18 @@ mon-process-finished-glob() {
 		done
 	fi
 
-	local msecs_file=$drive_msecs_dir/$drive_name
-	# shellcheck disable=SC2086 # variable contains multiple values
-	if [[ -s $msecs_file ]]
-	   then # shellcheck disable=SC2046 # files contains multiple values
-		set -- $(< "$msecs_file") $samples
-	   else set --			  $samples
+	local msecs_file=$drive_msecs_dir/$drive_name msecs_list
+	if [[ -s "$msecs_file" ]]
+	   then read-all msecs_list "$msecs_file"
+		# shellcheck disable=SC2086 # files have multiple values
+		set -- $msecs_list $samples
+	   else # shellcheck disable=SC2086 # files have multiple values
+		set --		   $samples
 	fi
 	while (( $# > $sample_count )) ; do shift; done
 	echo-to-file "$*" "$msecs_file"
+
+	[[ $drive_name == "$mon_overhead_drive_name" ]] && return
 
 	local   snapshots_dir=$snapshots_replica_dir/$drive_name
 	[[ -d  $snapshots_dir ]] || mkdir "$snapshots_dir"
@@ -1881,7 +1876,7 @@ mon-process-finished-glob() {
 	local glob_file=$_mon_globs_dir/$drive_name subdirs
 	lock-replica-of-snapshots --wait # 'w' action uses same locking
 	rm -f ./*
-	subdirs=$(< "$glob_file") || abort subdirs=
+	read-all subdirs "$glob_file"
 	# shellcheck disable=SC2086 # variable contains multiple values
 	[[ $subdirs ]] && touch $subdirs
 	touch -r "$glob_file" .
@@ -1934,6 +1929,7 @@ mon-look-for-finished-globs() {
 	   do	set -- "${drive_name2PID[@]}" # any backgrounded globbing?
 		if [[ $# == 0 ]]	      # if not, stop looking
 		   then [[ $_drive_name ]] && abort-function "logic error"
+			# except at startup, we already hold the lock (?)
 			lockpid --wait "$mon_initialized_lock_path" > $dev_null
 			set-epoch_msecs
 			local -i used_msecs=$epoch_msecs-$start_msecs
@@ -1967,7 +1963,7 @@ update-monitor-config() {
 	[[ ${1-} == -c ]] && { shift; local do_check=$true; } ||local do_check=
 	# shellcheck disable=SC2086
 	[[ $# == 0 ]] &&
-	    set-drive_names -a && set -- $drive_names $mon_overhead_drive_name
+	    set-drive_names -a && set -- $mon_overhead_drive_name $drive_names
 
 	pushd_ "$window_msecs_dir"
 
@@ -1983,15 +1979,16 @@ update-monitor-config() {
 		fi
 
 		[[ $drive_name == "$mon_overhead_drive_name" ]] &&
-		    drive_name=$1	# need a valid drive_name
-		# shellcheck disable=SC2154 # drv_name2XXX peopulated by func
+		    drive_name=${!#}	# need a valid drive_name
+
+		# shellcheck disable=SC2154 # drv_name2XXX populated by func
 		set-product 1000 \
 		"${drv_name2drive_response_averaging_window_secs[$drive_name]}"
 		echo-to-file "$product" "$window_msecs_file"
 	done
 
-	set -- $drive_dir_prefix/*[!~] #see set-max_drive_names-max_drive_count
-	[[ $# != "$max_drive_count" && $do_check ]] && exec $our_path monitor
+	# this caused infinite loop, killed it with: fuser -9 -k -v monitor.log
+	# [[ $do_check ]] && did-set-max_drive_names && exec $our_path monitor
 
 	popd_
 }
@@ -2009,7 +2006,9 @@ monitor-drives() {
 	create-status_dir &&
 	create-monitor-dirs || abort-function "couldn't create dirs"
 
-	set-max_drive_names-max_drive_count # for update-monitor-config
+	[[ $max_drive_names ]] ||
+	fully-populate-custom-config-maps # for update-monitor-config
+	update-monitor-config
 
 	exec &> "$_monitor_dir/monitor.log" # to catch problems
 
@@ -2031,12 +2030,12 @@ readonly -f monitor-drives
 
 # ----------------------------------------------------------------------------
 
-re-start-monitor-drives-if-needed() {
+function did-re-start-monitor-drives-if-needed() {
 	[[ ${1-} == -f ]] && { shift;local do_force=$true; } || local do_force=
 
 	[[ $UID == 0 ]] ||
 	{ sudo -n kill && sudo -n "$our_path"; } &> $dev_null ||
-	    return
+	    return 1
 
 	if [[ $do_force ]] ||
 	   ( [[ $our_path == /usr/* ]] &&   # are we the installed command?
@@ -2052,7 +2051,7 @@ re-start-monitor-drives-if-needed() {
 	is-active-lock "$drive_monitor_lock_path" ||
 	    sudo "$our_path" monitor-drives > $dev_null
 }
-readonly -f re-start-monitor-drives-if-needed
+readonly -f did-re-start-monitor-drives-if-needed
 
 
 ##############################################################################
@@ -2062,7 +2061,7 @@ readonly -f re-start-monitor-drives-if-needed
 function is-multi-writer-drive() {
 	local drive_name=${1:-$drive_name}
 
-	[[ $custom_config_vars ]] ||
+	[[ $max_drive_names ]] ||
 	fully-populate-custom-config-maps
 
 	local flag=$is_multi_writer_drive
@@ -2342,7 +2341,7 @@ save-stats-file() {
 		# a prune or copy could have been suspended by another writer
 		if [[ -s $data_file ]]
 		   then local stats_content
-			stats_content=$(< "$data_file") || abort stats_content=
+			read-all stats_content "$data_file"
 			if [[ $stats_content != [-0-9]* ]] # multiple writers?
 			   then popd_ -q
 				return
@@ -3076,7 +3075,7 @@ validate-prune_globs() {
 			for pruned
 			    do	[[ ! -s $pruned ]] &&
 				    echo "$span" > "$pruned" && continue
-				old_span=$(< "$pruned") || abort old_span=
+				read-all old_span "$pruned"
 				new_span=$span
 				abort "$pruned was pruned by spans $old_span and $new_span (first span is 1) in type2prune_type_globs[$type]"
 			done
@@ -4131,7 +4130,7 @@ set-backup_type() {
 	backup_type=${drive_name2backup_type[$drive_name]-}
 	[[ $backup_type ]] && return	# was it in the cache?
 
-	[[ $custom_config_vars ]] ||
+	[[ $max_drive_names ]] ||
 	fully-populate-custom-config-maps
 
 	backup_type=
@@ -4636,7 +4635,7 @@ function fill-in-unpruned-empty-snapshots() {
 	local skipped_copy_args_file=$tmp_5
 	local force_opt= # to force one copy per pass (if all sources are busy)
 	while true
-	    do	local args dst_snapshot=
+	    do	local args dst_snapshot= snap
 		local did_skip_a_snapshot=$false
 		while read -r args
 		    do	[[ $args ]] || abort "blank line in $srcs_dst_file"
@@ -4658,10 +4657,10 @@ function fill-in-unpruned-empty-snapshots() {
 			# shellcheck disable=SC2046,SC2086 # *_opt may be null
 			fastest-snapshots $force_opt "$@" \
 			        >  "$fastest_snapshots_file" # so no subprocess
-			# shellcheck disable=SC2046 # we want word splitting
-			set -- $(< "$fastest_snapshots_file")
-			if [[ $# != 0 ]]
-			   then copy-snapshot-rsync "$1" "$dst_snapshot" >&2
+			# shellcheck disable=SC2034 # foo is unused snapshots
+			read -r snap foo < "$fastest_snapshots_file"
+			if  [[ $snap ]]
+			   then copy-snapshot-rsync "$snap" "$dst_snapshot" >&2
 				status=0 # we did some work
 				# copy-* took a long time, recheck drive speeds
 				$IfRun unset drive_name2speed_record >&2
@@ -4747,7 +4746,7 @@ do-chores() {
 	check-logs			# create data for 'watch'
 	rm-dangling-stats-symlinks
 	rm-stale-locks			# do before ...
-	re-start-monitor-drives-if-needed
+	did-re-start-monitor-drives-if-needed
 	# log "$FUNCNAME finished"	# for debugging
 }
 readonly -f do-chores
@@ -4977,7 +4976,7 @@ function set-count-last-average-maximum-sum-files--from-stats-files() {
 	count=0  maximum=-1123456789  sum=0 # caller declares these -i
 	local file file_contents number
 	for file
-	    do	file_contents=$(< "$file") || abort file_contents=
+	    do	read-all file_contents "$file"
 		[[ $file_contents == [-0-9]* ]] || continue
 		number=$file_contents
 
@@ -5319,7 +5318,12 @@ function count-snapshots-being-created-on-drive() {
 	set-lock_paths backup,copy
 	# shellcheck disable=SC2086 # variable contains multiple values
 	set -- $lock_paths
-	[[ $# == 2 ]] && (( $(< "$1") == $(< "$2") )) && shift # duplicate PID?
+	if [[ $# == 2 ]]
+	   then local PID_1 PID_2
+		read -r PID_1 < "$1"
+		read -r PID_2 < "$2"
+		(( $PID_1 == $PID_2 )) && shift # duplicate PID?
+	fi
 
 	# count snapshots we're creating
 	local path
@@ -5401,14 +5405,17 @@ _recalculate-snapshot-stats-vars() {
 		restore-tracing
 
 		[[ $# != 0 ]] && {
+		local snapshots=$*
 		local partials=
 		local partials_file=$non_empty_partial_dir/$drive_name
 		[[ ! -s $partials_file ]] ||
-		    partials=$(< "$partials_file") || abort partials=
+		    read-all partials "$partials_file"
+		# shellcheck disable=SC2086 # want word splitting
+		set -- $partials ; partials=" $* " # SPACEs for matching, below
 		local snapshot snap prev_snap= snaps=
-		for snapshot in "$@"
+		for snapshot in $snapshots
 		    do	if [[ $skip_empty || $only_empty ]]
-			then [[ " $partials " == *" $snapshot "* ]] &&
+			then [[ $partials == *" $snapshot "* ]] &&
 				 local is_empty=$false || local is_empty=$true
 				[[ $skip_empty &&   $is_empty ]] && continue
 				[[ $only_empty && ! $is_empty ]] && continue
@@ -5472,7 +5479,9 @@ function _is-stats-cache-fresh {
 
 	[[ -s $cache_file ]] || return 1
 
-	if [[ $drive_names != "$(< "$cached_drive_names_file")" ]]
+	local cached_drive_names
+	read-all cached_drive_names "$cached_drive_names_file"
+	if [[ $drive_names != "$cached_drive_names" ]]
 	   then rm -f "$cached_drive_names_file" "$watch_cache_dir"/*/*,*.txt
 		return 1
 	fi
@@ -6587,6 +6596,8 @@ function generate() {
 	Trace 1 "$output_file from $function"
 
 	# wouldn't need polling if used a fifo, but they're buggy in bash-4.4
+	#    (and might block if generated too much output)
+	# fixme: could try to use a coproc
 	until [[ -s $rows_left_file ]] ; do msleep 1; done
 	read -r rows_left < "$rows_left_file" # let child modify our global
 
@@ -8598,11 +8609,14 @@ test-prune() {
 		header "prune '$type' snapshots, created by: mk-Z $mk_Z_args"
 		stash=.mk-Z.$type
 		$IfRun rm -rf "$stash".*.ls
-		for cmd in $old_cmd $tst_cmd
+		for cmd in $tst_cmd $old_cmd
 		    do	$IfRun clone-stashed-mk-Z "$type"
+			if [[ $cmd == "$old_cmd" ]]
+			   then which=old path="PATH=/usr/local/bin:$PATH"
+			   else which=new path=
+			fi
 			# shellcheck disable=SC2086 # *_opts has 0-n values
-			$IfRun $cmd $our_opts prune-drive Z
-			[[ $cmd == "$old_cmd" ]] && which=old || which=new
+			eval "$path \$IfRun \$cmd \$our_opts prune-drive Z"
 			ls > "$stash.$which.ls"
 		done
 		set-reversed_words "$stash".{old,new}.ls
@@ -8994,6 +9008,7 @@ case $action in
    # update-monitor-config: configure.sh's drive_response_averaging_window_secs
    ( upd*mon*conf* | mu | umc | um )
 	undo-action-abbrev update-monitor-config; $Trace
+	fully-populate-custom-config-maps
 	$action
 	;;
    # monitor-drives: start run-forever monitor of drive response time
