backup_period of 0 means don't do a backup. Correctly handle a larger number of similar syslog errors. If many syslog daddr errors, show them all on one line.

diff --git a/bin/snapback b/bin/snapback
--- a/bin/snapback
+++ b/bin/snapback
@@ -1733,6 +1733,7 @@ validate-config-variables() {
 	   abort "dirs_to_backup contains a non-absolute path in $*"
 
 	is-arg1-in-arg2 "$backup_period" "$valid_backup_periods" ||
+	   [[ "$backup_period" == 0 ]] ||
 	   abort "invalid 'backup_period=$backup_period' in $*"
 	declare -i backup_period
 
@@ -3674,6 +3675,7 @@ function _is-time-to-backup-drive {
 	set-excluded_hours $excluded_backup_hours
 	is-arg1-in-arg2 "$current_hour" "$excluded_hours" && return 1
 
+	(( $backup_period == 0 )) && return 1 # not backing up this drive?
 	(( $current_hour % $backup_period == 0 )) || return 1
 
 	# FIXME: need to send email if this happens
@@ -5049,7 +5051,7 @@ set-hour_avg-hour_max--from-files-of-minutes() {
 	set-customized_value--for-config-var-name backup_period &&
 	local -i backup_period=$customized_value
 	local -i backup_period_mins=$(( $backup_period*60 ))
-	if (( average >= backup_period_mins ))
+	if (( average >= backup_period_mins && backup_period_mins > 0 ))
 	   then if (( average == backup_period_mins ))
 		   then local type=warning
 		   else local type=error
@@ -6078,8 +6080,8 @@ show-errors-in-syslog() {
 
 	[[ ! ${no_errors-} && -s $errors_count_msg_file ]] && {
 
-	# shellcheck disable=SC2155  # 'basename' never fails
-	local header="count subset-of-$(basename "$syslog_path")-record"
+	# shellcheck disable=SC2155    # 'basename' never fails
+	local header=" count  subset-of-$(basename "$syslog_path")-record"
 	set-highlighted_string warning "${header^^}"
 	echo "$highlighted_string"
 	while read -r count msg
@@ -6094,7 +6096,7 @@ show-errors-in-syslog() {
 		    ( * ) local type=error   ;;
 		esac
 		set-highlighted_string $type "$msg"
-		printf "%5d: %s\n" "$count" "$highlighted_string"
+		printf "%6d: %s\n" "$count" "$highlighted_string"
 		(( rows_left-=1 ))
 	done < "$errors_count_msg_file"
 
@@ -8303,6 +8305,13 @@ search-syslog-for-errors() {
 	set -- $(sed -r -n 's/.* sector +([0-9]+)[^0-9]*/\1/p' "$file" |
 		 sort -u -n)
 	local sectors="$# sectors: $*"
+	#
+	# shellcheck disable=SC2046 # we want word splitting
+	set -- $(sed -r -n 's/.* daddr +(0x[0-9a-f]+)\b.*/\1/p' "$file" |
+		 sort -u)
+	# handle 1000 column screen
+	(( $# * 10 > 1000 )) && set -- "${@:1:1000/10}"
+	local daddrs="$# daddrs: $*"
 
 	local service_string="service: Failed to connect stdout to the journal"
 	# shellcheck disable=SC2046 # we want word splitting
@@ -8320,6 +8329,7 @@ search-syslog-for-errors() {
 		   -e  's/(blocks? +)[xa-f0-9]+/\1B/' \
 		   -e 's/( error 5 numblks? )[0-9]+/\1N/' \
 		   -e "s/(sectors? +)[0-9]+.*/$sectors/" \
+		   -e "s/(daddr +)[0-9a-xf]+.*/$daddrs/" \
 		   -e "s/^.*(\\.$service_string)/$services\\1/" |
 	    sort | sed 's/scrzz* /sd /' | # undo hack to group UAS msgs
 	    uniq -c | echo-to-file - "$cnt_msg_file" ||
@@ -8885,7 +8895,7 @@ case $action in
 	;;
 
    # big-swapouts: search syslog files for warnings about high swapout rates
-   ( big*swapouts | bs | so ) undo-action-abbrev big-swapouts
+   ( big*swapouts | so ) undo-action-abbrev big-swapouts
 	[[ $# == 0 ]] || abort-with-action-Usage
 	find-and-print-big-swapouts
 	;;
