Added new lock & unlock higher-level locking abstractions. old_new_snapshot_dates holds renames that yield snapshots that won't get pruned so fast.  We save the old-named snapshots by touching /.keep in them; we won't do the renames until we've merged all the off-site backups (which might have better candidates). Improve month pruning: leave xxxx-06-01,00 for a longer time. New 'run' action will run an internal function with args; pass "-v varnames" to show values of global variables it alters.

diff --git a/bin/snapback b/bin/snapback
--- a/bin/snapback
+++ b/bin/snapback
@@ -22,16 +22,17 @@ version=12			# has to match version= in configure.sh.sample
 
 readonly coder=sweikart@gmail.com
 
-# libsnap.sh has these funcs/vars: tmp_dir, our_name, our_path, true, false,
-# have_cmd, need_cmds, is_darwin, set_FS_type___from_path,
+# libsnap.sh has these functions/variables: $tmp_dir, $our_name, $our_path,
+# $true, $false, have_cmd, need_cmds, $is_darwin, set_FS_type___from_path,
 # set__inode_size__data_block_size__dir_block_size___from_path,
-# FS_label, set_FS_label___from_FS_device, label_drive,
-# set_FS_device___from_FS_label, set_device_KB___from_block_device, FS_device,
+# $FS_label, set_FS_label___from_FS_device, label_drive,
+# set_FS_device___from_FS_label, set_device_KB___from_block_device, $FS_device,
 # set_FS_device___from_path, set_mount_dir___from_FS_device,
 # set_mount_dir___from_FS_label,  set_FS_label___from_mount_dir,
 # warn, abort, echoE, echoEV, Trace, TraceV, suspend_tracing, restore_tracing,
-# log, file_for_logging, log_level, log_msg_prefix, header,
-# cd_ , add_words, confirm, is_arg1_in_arg2, abort_with_action_Usage
+# print_or_egrep_Usage_then_exit, abort_with_action_Usage,
+# log, $file_for_logging, $log_level, $log_msg_prefix, header,
+# cd_ , add_words, confirm, is_arg1_in_arg2, run_function
 #
 # search for '####' in libsnap.sh to see environment and coding conventions
 source libsnap.sh || exit 1
@@ -214,7 +215,7 @@ assert_drive_dir_writable() {
 }
 
 ##############################################################################
-# process and lock management
+# lock management
 ##############################################################################
 
 set_PGID() {
@@ -249,24 +250,29 @@ readonly lock_dir=/var/lock/$our_name
 lock_file=
 
 set_lock_file() {
+	suspend_tracing
+
 	local type=$1 name=${2:-$drive_name}
 
 	[[ -d $lock_dir ]] || sudo mkdir -p --mode=1777 $lock_dir
 
-	is_arg1_in_arg2 $type $lock_types || abort "lock: '$type' is unknown"
+	is_arg1_in_arg2 $type $lock_types ||
+	   abort "lock: '$type' is unknown lock type"
 
-	[[    $custom_config_vars ]] &&
-	local $custom_config_vars
-	suspend_tracing
+	[[     $custom_config_vars ]] &&
+	local ${custom_config_vars/suspend_prune_when_backup/} # for lock()
 	set_drive_name $name
-	restore_tracing
 	lock_file=$lock_dir/$type-$drive_name.pid
+
+	restore_tracing lock_file
 }
 
 # ---------------------------------
 
 run_lockpid() {
 	local lock_file=$1 lock_holder_action=$2
+	[[ $lock_holder_action == holds* ]] ||
+	    lock_holder_action="is $lock_holder_action"
 
 	local our_PID=$BASHPID
 	local lock_cmd="lockpid $lock_file $our_PID"
@@ -283,15 +289,92 @@ run_lockpid() {
 				sed 's@^Process @@; s@ holds lock .*@@')
 	if [[ $status == 1 && $lock_holder_PID ]]
 	   then [[ ! $is_cron || $(date '+%H') == 00 || $log_level -gt 0 ]] &&
-		log  "process $lock_holder_PID is $lock_holder_action"
+		log  "process $lock_holder_PID $lock_holder_action"
 	   else log "$lock_cmd -> $lockpid_output (status=$status)"
 	fi >&2
 	return 1
 }
 
-# --------------------------------
+# ------------------------------------------------------------------
+
+readonly  lock_wait_secs=0.2
+readonly lock_share_secs=0.5
+
+declare -A _lock_type2lock_file
+declare -A  lock_type2locked_resource
+
+# Usage: lock [-C | -w] type resource(s)
+#    Grab a lock of 'type' on any one of the resources (drive-dir or snapshot).
+#    If -C and want 'backup' lock but it's held by a Copy job, kill copy job.
+#    If -w and all locks are held by other jobs, Wait for a lock to be freed.
+#    Can't grab 'prune' lock if 'backup' lock held and should suspend prune.
+lock() {
+	local steal_copys_backup_lock=$false
+	[[ $1 == -C ]] && { shift; steal_copys_backup_lock=$true; }
+	[[ $1 == -w ]] && { shift; local do_wait=$true; } || local do_wait=
+	local type=$1; shift
+
+	$Trace
+	while true
+	    do	local resource lock_file
+		for resource
+		    do	local drive=${resource%/$snapshot_pattern*}
+			set_lock_file backup $drive
+			local backup_lock_file=$lock_file
+			set_lock_file $type  $drive
+
+			local prev_lock_file=${_lock_type2lock_file[$type]-}
+			[[   $prev_lock_file == $lock_file ]] &&
+			   { warn "already hold $lock_file"; return 0; }
+			[[ ! $prev_lock_file ]] ||
+			   abort "hold $prev_lock_file, can't grab $lock_file"
+
+			if [[ $type == backup && $steal_copys_backup_lock ]]
+			   then $IfRun lockpid $lock_file && return 0
+				local bPID=$(< $lock_file)
+				[[ $(fgrep -w $bPID $lock_dir/copy-*.pid) ]] &&
+				    { kill_jobs backup $drive
+				      do_wait=$true; } # wait for copy to die
+			fi >& /dev/null
+
+			if [[ $type == prune && $suspend_prune_when_backup ]]
+			   then $IfRun lockpid    $backup_lock_file || continue
+				$IfRun lockpid -r $backup_lock_file
+			fi >& /dev/null
+
+			local action_msg="holds '$type' lock for $drive"
+			if [[ $do_wait ]]
+			   then $IfRun lockpid $lock_file >& /dev/null
+			   else    run_lockpid $lock_file "$action_msg"
+			fi &&
+			    _lock_type2lock_file[$type]=$lock_file &&
+			     lock_type2locked_resource[$type]=$resource &&
+			    return 0
+		done
+		[[ $do_wait ]] || return 1
+		$IfRun sleep $lock_wait_secs
+	done
+}
+
+# ---------------------------------
+
+unlock() {
+	[[ $1 == -s ]] && { shift; local do_share=$true; } || local do_share=
+
+	local type
+	for type
+	    do	local lock_file=${_lock_type2lock_file[$type]-}
+		[[   $lock_file ]] || abort "don't hold lock of type '$type'"
+		$IfRun lockpid -r $lock_file
+		unset _lock_type2lock_file[$type]
+		unset  lock_type2locked_resource[$type]
+	done
+	[[ $do_share ]] && $IfRun sleep $lock_share_secs
+}
+
+##############################################################################
 # signaling/killing process groups
-# --------------------------------
+##############################################################################
 
 signal_is_kill=
 
@@ -794,6 +877,19 @@ _is_time_to_prune_drive() {
 
 # ----------------------
 
+# the old snapshots contain /.keep so won't be pruned; all are ,00
+declare -a old_new_snapshot_dates=(
+	"2016-08-01 2016-06-01"
+	"2017-03-28 2017-04-01"
+	"2017-05-24 2017-06-01"
+	"2017-07-16 2017-08-01"
+	"2017-09-16 2017-09-01"
+	"2017-10-24 2018-01-01"
+	"2018-04-22 2018-04-01"
+	"2018-05-03 2018-06-01"
+	"2019-01-13 2019-01-01"
+)
+
 _rm_pruned_snapshots() {
 	local snapshots_file=$1
 
@@ -814,7 +910,7 @@ _rm_pruned_snapshots() {
 
 	# first, rename snapshots to be pruned, so can see the pruning backlog
 	for snapshot
-	    do	[[ $snapshot != *.rm ]] &&
+	    do	[[ $snapshot != *.rm && ! -e $snapshot/.keep ]] &&
 		$IfRun mv $snapshot $snapshot.rm
 	done
 
@@ -975,12 +1071,13 @@ declare -A backup_period2minimal_snapshot_pattern=(
 )
 #
 # the [hour] chunks are the complement of the previous map's values
+type       type2prune_type_patterns >& /dev/null || # can have custom version
 declare -A type2prune_type_patterns=(
 # the ones these patterns skip: hour=00, day=01, month=01, year=00
 # period after prune: 2                4                 ~8          ~12   all
    [hour]=",?[13579]         ,{[02][26],1[048]}       ,{04,20}    ,{08,16} ,12"
     [day]="-{?[3579],[1-3]1} -{[02][26],1[048],30} -{04,12,20,28} -{08,24} -16"
-  [month]="-{0[3579],11}          -{02,06,10}        -{04,08,12}"
+  [month]="-{0[3579],11}          -{02,08,12}         -{04,10}       -06"
    [year]="  [13579]                 {2,6}              {4,8}"
 )
 
@@ -1685,8 +1782,8 @@ set_backup_period___from_snapshot() {
 
 # ---------------------------------
 
-# "fastest" snapshot is one ignored by cron, else largest backup_period,
-# since using this snapshot reduces chance we're killed for a needed backup
+# "fastest" snapshot is one ignored by cron (else largest backup_period),
+# since using this snapshot reduces chance we're killed for a needed backup.
 fastest_snapshots() {
 
 	local      backup_period snapshot
@@ -3368,7 +3465,7 @@ case $action in
 		diff -q $* && mv $stash.new.ls $stash.pruned.ls &&
 			      rm $stash.old.ls &&
 		   echo -e "\nSame results, see $stash*" && continue
-		abort "Regression, see: diff $*"
+		warn "regression, see: diff -u $*"
 	done
 
 	clone_stashed_mk_Z hour
@@ -3451,7 +3548,14 @@ case $action in
    # you can jump to the end of the file.			 #
    # -------------------------------------------------------------
 
+   ( run | r )
+	run_function "$@"		# can pass: -v varname(s)
+	;;
    ( test | t )
+	declare -a digit2name=(zero one two three)
+	echoEV action digit2name[2]
+	exit
+
 	$Trace
 	customize_config_variables ${1:-G}
 	exit
