If drive block or inode usage is 99%, don't do backups, since reported 99% could actually be 99.999%.

diff --git a/bin/snapback b/bin/snapback
--- a/bin/snapback
+++ b/bin/snapback
@@ -1342,6 +1342,10 @@ validate-config-variables() {
 	   abort "invalid 'backup_period=$backup_period' in $*"
 	declare -i backup_period
 
+	(( $max_FS_usage_percent >  0 )) &&
+	(( $max_FS_usage_percent < 99 )) || # 99% could be 99.999%
+	    abort "invalid: max_FS_usage_percent=$max_FS_usage_percent'"
+
 	[[ -s $exclude_file ]] ||
 	   abort "'exclude_file=$exclude_file' is empty file (from $*)"
 
@@ -1394,6 +1398,8 @@ readonly -f is-multi-writer-drive
 
 # ----------------------------------------------------------------------------
 
+declare -i highest_drive_usage
+
 function is-drive-usage-too-high() {
 	local drive_dir=${1:-$drive_dir}
 
@@ -1404,12 +1410,17 @@ function is-drive-usage-too-high() {
 	suspend-tracing
 	local -i pcent ipcent
 	setup-df-data-from-fields $drive_dir pcent ipcent
-	local block_percent=$pcent  inode_percent=$ipcent
+	local -i block_percent=$pcent inode_percent=$ipcent
 	if (( $block_percent > $inode_percent ))
 	   then max_drive_usage_percent=b$block_percent
 	   else max_drive_usage_percent=i$inode_percent
 	fi
 	restore-tracing
+
+	if (( $block_percent > $inode_percent ))
+	   then highest_drive_usage=$block_percent
+	   else highest_drive_usage=$inode_percent
+	fi
 	(( $block_percent <= $max_FS_usage_percent )) || return 0
 	(( $inode_percent <= $max_FS_usage_percent )) || return 0
 	return 1
@@ -2355,9 +2366,12 @@ function _is-time-to-run-backup {
 	set-excluded_hours $excluded_backup_hours
 	is-arg1-in-arg2 $current_hour $excluded_hours && return 1
 
-	(( $current_hour % $backup_period == 0 )) && return 0
+	(( $current_hour % $backup_period == 0 )) || return 1
 
-	return 1
+	# FIXME: need to send email if this happens
+	is-drive-usage-too-high && (( $highest_drive_usage >= 99 )) && return 1
+
+	return 0
 }
 readonly -f _is-time-to-run-backup
 
@@ -6109,6 +6123,10 @@ case $action in
    ( true )				# used to test for needed options
 	true ;;
    ( test | t ) undo-action-abbrev test; $Trace
+	set-drive_name ${1:-F}
+	set-drive_dir $drive_name
+	is-drive-usage-too-high && (( $highest_drive_usage >= 98 )); exit $?
+
 	set-drive_name ${1:-E}
 	set-drive_dir $drive_name
 	suspended-prune-as-drive-usage-response; echo $?; exit
